CREATE SCHEMA `spring-batch-dynamic-composite`;

CREATE TABLE `composite_batch_beans` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`TASK_NAME` VARCHAR(255) NOT NULL,
	`BATCH_BEAN_TYPE` VARCHAR(50) NULL DEFAULT NULL,
	`PRIORITY` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
);
